name: Run Unit Tests
on:
  pull_request:

jobs:
  test:
    name: "Run Tox"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - run: pip install tox
      - name: Running tox
        run: tox -e py
